#!/bin/bash

search="$(RANDOM=$((( -1 * (20200101 - $(date '+%Y%m%d'))))) ; grep $(($RANDOM % 1129 + 1)) bwv.txt)"

url="https://www.youtube.com/results?search_query=${search// /+}"

links=($(lynx --dump $url | awk '/watch\?.{13}$/ {print $2}' | head -n 5))

echo "Today's Bach is: $search
"
PS3="
Choose a link for a performance: "
COLUMNS=1
select link in "${links[@]}"; do
  break
done

$BROWSER "https://www.youtube.com$link"
